version: "3.7"

services:
  mongodb-Cont:
    image: mongo:latest
    container_name: mongoDB-Cont
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_DATABASE=mongoDB-Cont
    volumes:
      - mongodb_data_cont:/data/db

volumes:
  mongodb_data_cont:
